@startuml

abstract class Offer {
    - id : int
    - user : User
    - title : string
    - description : string
    - price : float
    - priceType : PriceType
    - startingDate
    - endingDate
}

enum PriceType {
    euro/hour
    euro/day
}


class Product extends Offer {
    - category : ProductCategory
    - brand : string
    - model : string
    - year : int
    - condition : ProductCondition
    - images : Image[]
}

enum ProductCategory {
    Auto,
    Jardin,
    Maison,
    Mode,
    Multimedia,
    Sport,
    Autre
}

class Service extends Offer {

}

class Rating {
    - id : int
    - offer : Offer
    - user : User
    - value : float
    - comment : string
}


class Booking {
    - id : int
    - offer : Offer
    - user : User
    - startingDate
    - endingDate
    - status : BookingStatus
}

enum BookingStatus {
    Pending,
    Accepted,
    Refused,
    Cancelled,
    Finished
}

class Waiting {
    - id : int
    - offer : Offer
    - user : User
    - askingDate
    - status : WaitingStatus
}

enum WaitingStatus {
    Pending,
    Accepted,
    Refused,
    Finished,
    Cancelled
}

enum ProductCondition {
    New,
    Good,
    Used,
    Refurbished
}


@enduml