@startuml

abstract class Person {
    - id : int
    - firstName : string
    - lastName : string
    - email : string
    - password : string
    - phone : string
    - balance : float
}

Person *-- Address

class Address {
    - id : int
    - address : string
}

class User extends Person {

}

class Admin extends Person {

}

@enduml